/**
 * Generates a plain Wavefront OBJ solid representing a crane's full swept
 * ("swing envelope") volume: a vertical wedge/cylinder sector.
 *
 * Why OBJ and not Trimble's .trimbim format: .trimbim is a proprietary
 * binary format Trimble's own tools *export* to (e.g. Connect for Windows'
 * "Export as TrimBIM"), but there's no public spec for *authoring* one from
 * scratch. OBJ is a plain, well-understood format that Connect's standard
 * upload/conversion pipeline ingests like any other CAD file, so the
 * envelope can go through the same "upload -> auto-convert -> place" path
 * as the crane model itself. See PLAN.md §4.
 *
 * The origin (0,0,0) is the crane's slew/pivot point at its base. Position
 * the exported model there via viewer.placeModel once it's imported.
 */

export interface SwingEnvelopeParams {
  /** Horizontal boom reach from the pivot point, in metres. */
  radiusM: number;
  /** Lowest point of the swept volume (e.g. ground or hook-low), in metres. */
  minHeightM: number;
  /** Highest point of the swept volume (e.g. max boom tip height), in metres. */
  maxHeightM: number;
  /** Slew start angle in degrees, measured counter-clockwise from +X. */
  slewStartDeg: number;
  /** Slew end angle in degrees. Use 0/360 for a full-circle sweep. */
  slewEndDeg: number;
  /** Number of segments used to approximate the arc. Higher = smoother, bigger file. */
  segments?: number;
}

export function generateSwingEnvelopeObj(params: SwingEnvelopeParams): string {
  const {
    radiusM,
    minHeightM,
    maxHeightM,
    slewStartDeg,
    slewEndDeg,
    segments = 48,
  } = params;

  if (radiusM <= 0) throw new Error("radiusM must be > 0");
  if (maxHeightM <= minHeightM) throw new Error("maxHeightM must be > minHeightM");

  const isFullCircle = Math.abs(((slewEndDeg - slewStartDeg) % 360 + 360) % 360) < 1e-6
    || Math.abs(slewEndDeg - slewStartDeg) >= 360;

  const startRad = (slewStartDeg * Math.PI) / 180;
  const endRad = (slewEndDeg * Math.PI) / 180;
  const sweepRad = isFullCircle ? 2 * Math.PI : endRad - startRad;
  const stepCount = Math.max(3, segments);
  const angleStep = sweepRad / stepCount;
  // For a full circle the last point coincides with the first, so drop it.
  const pointCount = isFullCircle ? stepCount : stepCount + 1;

  const lines: string[] = [
    "# Crane swing envelope",
    `# radius=${radiusM}m minHeight=${minHeightM}m maxHeight=${maxHeightM}m ` +
      `slew=${slewStartDeg}..${slewEndDeg}deg`,
    "# Generated by trimble-crane-clearance-extension — see PLAN.md",
  ];

  // Vertices: bottom ring, top ring, then (if not full circle) the pivot
  // point duplicated at bottom and top for the two flat end caps.
  const bottomRingStart = 1; // OBJ indices are 1-based
  for (let i = 0; i < pointCount; i++) {
    const a = startRad + i * angleStep;
    lines.push(`v ${(radiusM * Math.cos(a)).toFixed(4)} ${(radiusM * Math.sin(a)).toFixed(4)} ${minHeightM.toFixed(4)}`);
  }
  const topRingStart = bottomRingStart + pointCount;
  for (let i = 0; i < pointCount; i++) {
    const a = startRad + i * angleStep;
    lines.push(`v ${(radiusM * Math.cos(a)).toFixed(4)} ${(radiusM * Math.sin(a)).toFixed(4)} ${maxHeightM.toFixed(4)}`);
  }

  let pivotBottomIdx = -1;
  let pivotTopIdx = -1;
  if (!isFullCircle) {
    lines.push(`v 0.0000 0.0000 ${minHeightM.toFixed(4)}`);
    pivotBottomIdx = topRingStart + pointCount;
    lines.push(`v 0.0000 0.0000 ${maxHeightM.toFixed(4)}`);
    pivotTopIdx = pivotBottomIdx + 1;
  }

  const faces: string[] = [];

  // Side wall (quad strip between bottom and top ring).
  const ringSegCount = isFullCircle ? pointCount : pointCount - 1;
  for (let i = 0; i < ringSegCount; i++) {
    const b0 = bottomRingStart + i;
    const b1 = bottomRingStart + ((i + 1) % pointCount);
    const t0 = topRingStart + i;
    const t1 = topRingStart + ((i + 1) % pointCount);
    faces.push(`f ${b0} ${b1} ${t1} ${t0}`);
  }

  // Bottom and top caps (fan from the pivot for a partial sweep; full disc for 360°).
  if (isFullCircle) {
    // Fan from first ring point for bottom/top discs.
    for (let i = 1; i < pointCount - 1; i++) {
      faces.push(`f ${bottomRingStart} ${bottomRingStart + i} ${bottomRingStart + i + 1}`);
      faces.push(`f ${topRingStart} ${topRingStart + i + 1} ${topRingStart + i}`);
    }
  } else {
    for (let i = 0; i < pointCount - 1; i++) {
      faces.push(`f ${pivotBottomIdx} ${bottomRingStart + i} ${bottomRingStart + i + 1}`);
      faces.push(`f ${pivotTopIdx} ${topRingStart + i + 1} ${topRingStart + i}`);
    }
    // Flat end caps (the two straight radial faces at slewStart / slewEnd).
    faces.push(`f ${pivotBottomIdx} ${bottomRingStart} ${topRingStart} ${pivotTopIdx}`);
    const lastBottom = bottomRingStart + pointCount - 1;
    const lastTop = topRingStart + pointCount - 1;
    faces.push(`f ${pivotBottomIdx} ${pivotTopIdx} ${lastTop} ${lastBottom}`);
  }

  return [...lines, ...faces].join("\n") + "\n";
}

export function triggerObjDownload(objText: string, filename = "envelope.obj"): void {
  const blob = new Blob([objText], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
