/**
 * Crane Clearance Checker — plain JavaScript, no build step.
 *
 * This replaces the TypeScript version (main.ts / workspace.ts /
 * geometry/swing-envelope.ts) with a single file that runs directly in the
 * browser as-is — GitHub Pages (or any static host) can serve it with no
 * compilation. index.html loads the real Trimble Connect Workspace API
 * library from a CDN (see the <script> tag above this one in index.html)
 * as the global `TrimbleConnectWorkspace`, confirmed from the published
 * package's IIFE bundle:
 *   https://unpkg.com/trimble-connect-workspace-api/dist/iife/trimbleconnect.workspace.api.js
 * which attaches `window.TrimbleConnectWorkspace.connect(targetWindow, eventHandler, timeout)`.
 *
 * The ViewerAPI method names used below (getModels, toggleModel,
 * placeModel, getObjectBoundingBoxes, setSelection, getObjects, etc.) are
 * confirmed from Trimble's published API reference — see PLAN.md §2.1.
 * The exact payload shape for placeModel is still a best guess pending a
 * live test against a real project — flagged inline below.
 */

// ---- Workspace API connection ---------------------------------------------

let apiPromise = null;

function getWorkspaceApi() {
  if (!apiPromise) {
    apiPromise = TrimbleConnectWorkspace.connect(
      window.parent,
      (event, data) => {
        console.log("[workspace-api event]", event, data);
      },
      1000,
    );
  }
  return apiPromise;
}

async function ensureAccessToken() {
  const api = await getWorkspaceApi();
  return new Promise((resolve, reject) => {
    const timeout = setTimeout(() => reject(new Error("Timed out waiting for access token")), 30000);
    api.extension.on("accessToken", (token) => {
      clearTimeout(timeout);
      resolve(token);
    });
    api.extension.requestPermission("accessToken");
  });
}

// ---- Swing envelope geometry (Wavefront OBJ) -------------------------------

function generateSwingEnvelopeObj(params) {
  const {
    radiusM,
    minHeightM,
    maxHeightM,
    slewStartDeg,
    slewEndDeg,
    segments = 48,
  } = params;

  if (radiusM <= 0) throw new Error("radiusM must be > 0");
  if (maxHeightM <= minHeightM) throw new Error("maxHeightM must be > minHeightM");

  const isFullCircle =
    Math.abs((((slewEndDeg - slewStartDeg) % 360) + 360) % 360) < 1e-6 ||
    Math.abs(slewEndDeg - slewStartDeg) >= 360;

  const startRad = (slewStartDeg * Math.PI) / 180;
  const endRad = (slewEndDeg * Math.PI) / 180;
  const sweepRad = isFullCircle ? 2 * Math.PI : endRad - startRad;
  const stepCount = Math.max(3, segments);
  const angleStep = sweepRad / stepCount;
  const pointCount = isFullCircle ? stepCount : stepCount + 1;

  const lines = [
    "# Crane swing envelope",
    `# radius=${radiusM}m minHeight=${minHeightM}m maxHeight=${maxHeightM}m ` +
      `slew=${slewStartDeg}..${slewEndDeg}deg`,
    "# Generated by trimble-crane-clearance-extension — see PLAN.md",
  ];

  const bottomRingStart = 1;
  for (let i = 0; i < pointCount; i++) {
    const a = startRad + i * angleStep;
    lines.push(
      `v ${(radiusM * Math.cos(a)).toFixed(4)} ${(radiusM * Math.sin(a)).toFixed(4)} ${minHeightM.toFixed(4)}`,
    );
  }
  const topRingStart = bottomRingStart + pointCount;
  for (let i = 0; i < pointCount; i++) {
    const a = startRad + i * angleStep;
    lines.push(
      `v ${(radiusM * Math.cos(a)).toFixed(4)} ${(radiusM * Math.sin(a)).toFixed(4)} ${maxHeightM.toFixed(4)}`,
    );
  }

  let pivotBottomIdx = -1;
  let pivotTopIdx = -1;
  if (!isFullCircle) {
    lines.push(`v 0.0000 0.0000 ${minHeightM.toFixed(4)}`);
    pivotBottomIdx = topRingStart + pointCount;
    lines.push(`v 0.0000 0.0000 ${maxHeightM.toFixed(4)}`);
    pivotTopIdx = pivotBottomIdx + 1;
  }

  const faces = [];

  const ringSegCount = isFullCircle ? pointCount : pointCount - 1;
  for (let i = 0; i < ringSegCount; i++) {
    const b0 = bottomRingStart + i;
    const b1 = bottomRingStart + ((i + 1) % pointCount);
    const t0 = topRingStart + i;
    const t1 = topRingStart + ((i + 1) % pointCount);
    faces.push(`f ${b0} ${b1} ${t1} ${t0}`);
  }

  if (isFullCircle) {
    for (let i = 1; i < pointCount - 1; i++) {
      faces.push(`f ${bottomRingStart} ${bottomRingStart + i} ${bottomRingStart + i + 1}`);
      faces.push(`f ${topRingStart} ${topRingStart + i + 1} ${topRingStart + i}`);
    }
  } else {
    for (let i = 0; i < pointCount - 1; i++) {
      faces.push(`f ${pivotBottomIdx} ${bottomRingStart + i} ${bottomRingStart + i + 1}`);
      faces.push(`f ${pivotTopIdx} ${topRingStart + i + 1} ${topRingStart + i}`);
    }
    faces.push(`f ${pivotBottomIdx} ${bottomRingStart} ${topRingStart} ${pivotTopIdx}`);
    const lastBottom = bottomRingStart + pointCount - 1;
    const lastTop = topRingStart + pointCount - 1;
    faces.push(`f ${pivotBottomIdx} ${pivotTopIdx} ${lastTop} ${lastBottom}`);
  }

  return [...lines, ...faces].join("\n") + "\n";
}

function triggerObjDownload(objText, filename = "envelope.obj") {
  const blob = new Blob([objText], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ---- UI wiring --------------------------------------------------------------

const statusEl = document.getElementById("status");
const modelSelect = document.getElementById("model-select");

function setStatus(msg) {
  statusEl.textContent = msg;
  console.log("[status]", msg);
}

document.getElementById("browse-warehouse")?.addEventListener("click", () => {
  window.open("https://3dwarehouse.sketchup.com/", "_blank", "noopener");
  setStatus(
    "Opened 3D Warehouse in a new tab. Download your model (Collada .dae or " +
      ".skp), then upload it into this project's Files. Once it's finished " +
      "converting, hit “Refresh model list” below.",
  );
});

document.getElementById("refresh-models")?.addEventListener("click", async () => {
  try {
    setStatus("Loading model list...");
    const api = await getWorkspaceApi();
    const models = await api.viewer.getModels();
    modelSelect.innerHTML = "";
    for (const model of models) {
      const opt = document.createElement("option");
      opt.value = model.id;
      opt.textContent = model.name;
      modelSelect.appendChild(opt);
    }
    setStatus(`Found ${models.length} model(s) in this project.`);
  } catch (err) {
    setStatus(`Couldn't load models: ${err.message}`);
  }
});

document.getElementById("place-model")?.addEventListener("click", async () => {
  const modelId = modelSelect.value;
  if (!modelId) {
    setStatus("Pick a model from the list first (refresh if it's empty).");
    return;
  }
  const x = Number(document.getElementById("pos-x").value);
  const y = Number(document.getElementById("pos-y").value);
  const z = Number(document.getElementById("pos-z").value);
  const rotZDeg = Number(document.getElementById("rot-z").value);

  try {
    setStatus("Loading model into view...");
    const api = await getWorkspaceApi();
    await api.viewer.toggleModel({ modelId, isVisible: true, fitToView: true });

    setStatus("Placing model...");
    // Exact placeModel payload shape is a best guess pending a live test —
    // see the header note and PLAN.md §2.1.
    await api.viewer.placeModel({
      modelId,
      position: { x, y, z },
      rotation: { x: 0, y: 0, z: rotZDeg },
    });

    setStatus(`Placed at (${x}, ${y}, ${z}), rotated ${rotZDeg}° about Z.`);
  } catch (err) {
    setStatus(`Placement failed: ${err.message}`);
  }
});

document.getElementById("download-envelope")?.addEventListener("click", () => {
  const radiusM = Number(document.getElementById("boom-radius").value);
  const minHeightM = Number(document.getElementById("boom-min-h").value);
  const maxHeightM = Number(document.getElementById("boom-max-h").value);
  const slewStartDeg = Number(document.getElementById("slew-start").value);
  const slewEndDeg = Number(document.getElementById("slew-end").value);

  try {
    const obj = generateSwingEnvelopeObj({ radiusM, minHeightM, maxHeightM, slewStartDeg, slewEndDeg });
    triggerObjDownload(obj, "swing-envelope.obj");
    setStatus(
      "Downloaded swing-envelope.obj. Upload it into this project like any " +
        "other model, then place it at the crane's base point (step 2) " +
        "using position (0,0,0) relative to wherever you place the crane.",
    );
  } catch (err) {
    setStatus(`Couldn't generate envelope: ${err.message}`);
  }
});

getWorkspaceApi()
  .then(() => setStatus("Connected to Trimble Connect."))
  .catch((err) => setStatus(`Couldn't connect to Trimble Connect: ${err.message}`));
